apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-b.fullname" . }}
  labels:
    {{- include "service-b.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "service-b.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.serviceB.containerPort }}
      targetPort: http

