environment: {}

serviceB:
  replicaCount: 1
  image:
    repository: local/service-b
    tag: local
    pullPolicy: IfNotPresent

  containerPort: 8080
  appEnv: ""

  probes:
    readinessPath: /healthz
    livenessPath: /healthz
    readinessInitialDelaySeconds: 5
    livenessInitialDelaySeconds: 10

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
  podSecurityContext: {}

  serviceAccount:
    create: true
    name: ""

  rbac:
    enabled: true

  config:
    logLevel: info

  secret:
    appToken: ""

