apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker.fullname" . }}-config
  labels:
    {{- include "worker.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.worker.config.logLevel | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worker.fullname" . }}-secret
  labels:
    {{- include "worker.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_TOKEN: {{ .Values.worker.secret.appToken | quote }}

